# 2020-fms GitHub Action config
#
# Action that runs on pushes to master and pull requests
#     - compile all code and documentation
#     - run any tests
#
# @version v1.0
# @author Connor Henley, @thatging3rkid
name: Pre-master Integration Testing

on:
    # Run on every push to master
    push:
        branches:
            - 'master'
    # Run on pull requests
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2 # checkout the repository

    # have to checkout the submodule before building (and this is the recommended way)
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recurs

    # mark that we're running a full build
    - name: Setup
      run: touch config.full

    # build all the code
    - name: Build
      run: make ci-build

    # run tests
    - name: Test
      run: make ci-test
